// /*
//  * This Java source file was generated by the Gradle 'init' task.
//  */
// package eStoreSearch;
// import java.util.Scanner;
// import java.util.*;

// public class eStore{
// /**
//  * 
//  * @param args taking in input to compare the what options the user wants
//  */
//     public static void main(String[] args) {
//         Scanner keyboard = new Scanner(System.in);
//         Scanner keyboard2 = new Scanner(System.in);
//         int i = 0;
//         int out= 0;
//         ArrayList <Product> productList = new ArrayList<Product>();
//         //Array list for searches
//         ArrayList <EStoreSearch> searchList = new ArrayList<EStoreSearch>();
//         String arg1,arg2 ;
//         int out2 = 0;
//         int check = 0;
//         // Window win = new Window();
//         // win.initWin(store);
//         // win.setVisible(true);
//           if (args.length < 1 ){
              
//           } else {
//              String inputFile = args[0];
//             readerFile one = new readerFile (); 
//              one.fileInitializer(inputFile,productList);
//           }
//           ///////////////////////////////
//         //   Giu newGiu = new Giu();
//         //   NewGui.setVisible(true);
//           ///////////////////////////////
//         do {
//             System.out.println("Choose the option you want for eStoreSearch : add  ,  search  ,  quit .");
//             arg1 = keyboard.nextLine();
           
//             if (arg1.equals("add")){
//                 System.out.println("For adding : "+"\n"+"(1) type (Book) or (b) for adding book "+"\n"+"(2) type (electronic) or (e) for adding electronic"+"\n"+"(3) type (back) for previous option");
//                 arg2 = keyboard2.nextLine();
              
//                     if(arg2.equalsIgnoreCase("Book") || arg2.equalsIgnoreCase("b")){
//                         /*add Book here*/ 
//                         Book retBook = new Book();
//                         retBook.initializeBook();
//                         productList.add(retBook);
//                          // if duplicate has been detected, delete it
//                         retBook.checkDuplicate(productList);                    
//                     } else if (arg2.equalsIgnoreCase("electronic")|| arg2.equalsIgnoreCase("e")){
//                         /* add electronic here */
//                         Electronics retElec = new Electronics();
//                         retElec.initializeElectronics();
//                         productList.add(retElec);  
//                         // if duplicate has been detected, delete it
//                        retElec.checkDuplicate(productList);
//                     }


//             }else if (arg1.equals("search")){
//                 // if we want to store then make an add for storing the result for searches  
//                 EStoreSearch system = new EStoreSearch(productList);
//                 searchList.add(system);
//                system.makeMap(productList);

//             }else if (arg1.equalsIgnoreCase("quit") || arg1.equalsIgnoreCase("q")){
//                 out = 1;
//             }
//             i++;
            
//         } while (out != 1);
//         // the loop ends here and so does the program
//         // once the program ends, this is for the output file
//         if (out ==1){
//             readerFile one = new readerFile (); 
//             one.fileOutputter (productList);
//         }
        
//     }
   
// }